name: Nightly DataBento L2 Backfill (Dry-Run)

on:
  schedule:
    # 02:00 ET -> 06:00 UTC (accounts for ET=UTC-4 during DST). Adjust if DST changes.
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  backfill:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: INFO
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Validate environment
        run: |
          # Use module path; the tool lives under src/tools/
          python -m src.tools.validate_env

      - name: Dry-run discovery (no vendor calls)
        run: |
          python src/tools/auto_backfill_from_warrior.py --since 3 --dry-run > dryrun_preview.json || true

      - name: Upload artifacts (dry-run preview)
        uses: actions/upload-artifact@v3
        with:
          name: l2-backfill-dryrun
          path: |
            dryrun_preview.json
