name: validate-tf1-manifest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Locate TF_1 manifest artifact
        run: |
          echo "::group::Find manifest"
          test -f examples/tf1_export_manifest.sample.json && echo "examples/tf1_export_manifest.sample.json" > MANIFEST_PATH || true
          echo "::endgroup::"
      - name: Validate manifest (PASS when alias present)
        if: hashFiles('MANIFEST_PATH') != ''
        env:
          CONTRACTS_DIR: contracts
        run: |
          MP=$(cat MANIFEST_PATH)
          python -m src.tools.validate_export_manifest --manifest "$MP"
      - name: Validate manifest (FAIL when alias missing)
        if: hashFiles('MANIFEST_PATH') != ''
        env:
          CONTRACTS_DIR: contracts
        run: |
          MP=$(cat MANIFEST_PATH)
          python -c "import json,sys; d=json.load(open(sys.argv[1])); d['model']['metadata']['production'].pop('alias',None); json.dump(d, open('no_alias.json','w'))" "$MP"
          python -m src.tools.validate_export_manifest --manifest no_alias.json && exit 1 || echo "Expected failure OK"
